baseURL = "https://example.com"
languageCode = "en-us"
title = "阿伦的仓库"
theme = "rocinante"
pagerSize = 3
summaryLength = 0

[markup]
  [markup.highlight]
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe= true

[author]
  name = "Sid Verma"

[params]
  mainSections = ["post", "photos"]
  email = "alun.h@qq.com"
  favicon = "icon/favicon.jpg"
  about = """
这里是阿伦的个人记录空间，不定时更新，随时删档重来


"""

  [[params.links]]
    
      
      
    [[params.links.link]]
      name = "Email"
      href = "/contact"
      smart_email_link = true
