baseURL = "https://example.com"
languageCode = "en-us"
title = "阿伦的仓库"
theme = "rocinante"
pagerSize = 3
summaryLength = 0

[markup]
  [markup.highlight]
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe= true

[author]
  name = "Sid Verma"

[params]
  mainSections = ["post", "photos"]
  email = "alun.h@qq.com"
  favicon = "icon/favicon.jpg"
  about = """



"""

  [[params.links]]
    [[params.links.link]]
      name = "About"
      href = "https://github.com/mavidser/hugo-rocinante?tab=readme-ov-file"
      new_tab = true
    [[params.links.link]]
      name = "Email"
      href = "/contact"
      smart_email_link = true
